### ISSUE TITLE
Failed to download package 'Macad.ThirdParty.Occt.7.7.0'

### ISSUE THREAD

**Issue by freeNastran** [Macad3D/Macad3D#62]
Hi,

7.8 is out. So the link is not exist anymore. Need update.

Cheers

**Comment by dipts** [comment]
The package still exists and is still in use. Please check if your Visual Studio version is up to date to support package source mapping. If it still does not work, please share the output of the restore command.

**Comment by freeNastran** [comment]
Tried again and it worked.

Test all has two errors. Where is Results (nunit3) saved as TestResult_UI.xml?

err 1:

`EXEC : 1) error : Macad.Test.UI.Application.Edit.ViewportTests.MoveAwayClosesContextMenu [D:\00master\Macad3D-main\Sour
ce\Test.UI\Test.UI.csproj]
  System.Runtime.InteropServices.COMException : An event was unable to invoke any of the subscribers (0x80040201)
     at Interop.UIAutomationClient.IUIAutomationElement.GetCurrentPropertyValueEx(Int32 propertyId, Int32 ignoreDefault
  Value)
     at FlaUI.Core.FrameworkAutomationElementBase.TryGetPropertyValue[T](PropertyId property, T& value)
     at FlaUI.Core.Input.Wait.UntilResponsive(AutomationElement automationElement, TimeSpan timeout)
     at Macad.Test.UI.Framework.ViewportAdaptor.MoveRelative(Double x, Double y, Boolean jump) in D:\00master\Macad3D-m
  ain\Source\Test.UI\Framework\ViewportAdaptor.cs:line 34
     at Macad.Test.UI.Framework.ViewportAdaptor.ClickRelative(Double x, Double y, MouseButton button, Boolean jump) in
  D:\00master\Macad3D-main\Source\Test.UI\Framework\ViewportAdaptor.cs:line 55
     at Macad.Test.UI.Application.Edit.ViewportTests.MoveAwayClosesContextMenu() in D:\00master\Macad3D-main\Source\Tes
  t.UI\Application\Edit\ViewportTests.cs:line 98`

err 2:

`D:\00master\Macad3D-main\Build\MSBuild\Macad.Test.targets(22,5): error MSB3073: The command "C:\Users\Cean\.nuget\packa
ges\nunit.consolerunner\3.16.0\tools\nunit3-console.exe D:\00master\Macad3D-main\bin\Release\Test.UI.dll --noheader --w
orkers=1 --result=TestResult_UI.xml --out=TestOutput_UI.txt" exited with code 3. [D:\00master\Macad3D-main\Source\Test.
UI\Test.UI.csproj]
Build failed.`

**Comment by dipts** [comment]
The file TestResult_UI.xml should be in the binary folder.

The framework behind the UI tests is unfortunately still a bit unstable, so it is possible that sometimes a test fails due to problems accessing the UI controls.
